import "../globals.css";

import { Footer } from "../../components/shared/footer/Footer";
import Topbar from "../../components/shared/Topbar/Topbar";

export const metadata = {
  title: "Autocion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Topbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
